# Generated by Django 4.2.28 on 2026-02-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='capa',
            field=models.ImageField(default='projetos/capas/default.png', upload_to='projetos/capas/'),
        ),
    ]
